[types] Remove unnecessary deps and add no_std support
paritytech/jsonrpsee pull request #261
Opened 2021-04-02 22:55 UTC by c410-f3r

For `jsonrpsee-types` alone, `cargo build` went down from `57` to `47` crates.

2021-04-03 10:23 UTC, niklasad1 commented on types/src/v2/error.rs
> +			Self::InvalidParams => write!(f, "invalid paramsr"),
```suggestion
			Self::InvalidParams => write!(f, "invalid params"),
```

2021-04-03 10:35 UTC, niklasad1 reviewed
Thanks for your PR.

Looks overall good but I don't really understand the rationale behind making this crate `no-std` without the client traits then it's not super useful, such as the proc macros wouldn't work. I suppose making the `SubscriptionClient trait` std only (subscription type) and make `Client trait` no-std would do it.

Can you elaborate why making the `no-std` is useful?

2021-04-03 10:56 UTC, c410-f3r commented
`no_std` support is usually a complementary and natural step when removing unnecessary dependencies. Besides, isn't it something desirable in the long run?

If necessary, I can remove `no_std` stuff. No problem.

2021-04-03 14:09 UTC, niklasad1 commented
> no_std support is usually a complementary and natural step when removing unnecessary dependencies. Besides, isn't it something desirable in the long run?

Sure, why not it introduces some boiler plate code for the `error stuff` but worth it if somebody wants to use the types in `no-std` but we have no plans making client/server to support for `no-std` but we have plans to move the [HTTP client to use surf as backend for WASM support](https://github.com/paritytech/jsonrpsee/issues/227)

2021-04-03 14:11 UTC, niklasad1 requested changes
LGTM except the typo, see inline suggestion.

2021-04-03 14:11 UTC, niklasad1 approved these changes

2021-04-03 14:17 UTC, c410-f3r commented
IIRC, `WASM` language isn't aware of `std` stuff (filesystem, threads, timer, etc) and that is one of the reasons for the creation of `WASI`.

2021-04-03 15:02 UTC, niklasad1 commented
> IIRC, WASM language isn't aware of std stuff (filesystem, threads, timer, etc) and that is one of the reasons for the creation of WASI.

Yes, but it's possible to do with `JavaScript bindings` too as [surf/http-client](https://github.com/http-rs/http-client) does.

2021-04-03 15:17 UTC, c410-f3r commented
Cool! Thanks for the link

2021-04-12 11:43 UTC, dvdplm requested changes
Reducing compile times is great, thank you so much for looking into this.

I agree with @niklasad1 that `no-std` is not a goal and adds more noise than it's worth imo. I also think that the added boilerplate around errors is questionable. I prefer it the way it was.

Any chance we can keep the compile time improvements without the inlining, no-std, and error re-implementations?

2021-04-12 11:43 UTC, dvdplm commented on types/src/error.rs
> +	#[inline]
Let's not try to outsmart the compiler; formatting errors is not on the hot path for anything so please remove the inlining hints.

2021-04-12 11:43 UTC, dvdplm commented on types/src/error.rs
> +	#[inline]
same

2021-04-13 10:16 UTC, niklasad1 commented on types/src/v2/traits.rs
>  trait RpcResult {
please merge with master, this was removed recently.

2021-04-13 11:01 UTC, niklasad1 commented
@dvdplm please take another look at this PR ^^

2021-04-13 14:37 UTC, dvdplm approved these changes

2021-04-13 14:37 UTC, merged