Add HTTP(S) proxy support
paritytech/jsonrpsee pull request #975
Opened 2023-01-19 01:05 UTC by allquixotic

This seems to work with both HTTP and HTTPS sites when using the jsonrpsee_http_client crate, allowing you to put a proxy in between your client and the endpoint. Very useful for debugging. Works with Proxyman, the proxy I'm using.

2023-01-19 08:53 UTC, niklasad1 commented on client/http-client/src/client.rs
> +	proxy: Option<String>,
```suggestion
	proxy: Option<Uri>,
```

2023-01-19 08:55 UTC, niklasad1 commented on client/http-client/Cargo.toml
> +hyper-proxy = { version = "0", default-features = false, features = ["rustls"] }
it should be possible to disable tls and not bring all these deps

```suggestion
hyper-proxy = { version = "0.9", default-features = false }
```

2023-01-19 09:03 UTC, niklasad1 commented on client/http-client/src/transport.rs
> +						let proxy_uri = pr.parse().unwrap();
```suggestion
						let proxy_uri = pr.parse().map_err(|e| Error::Url(format!("Invalid proxy URI: {}", e)))?;
```

2023-01-19 09:05 UTC, niklasad1 commented on client/http-client/src/client.rs
> +	pub fn set_proxy(mut self, proxy: String) -> Self {
would be better to return `Result<Self, Error>` and to parse proxy URI directly here.

```rust
	pub fn set_proxy(mut self, proxy: impl AsRef<str>) -> Result<Self, Error> {
      self.proxy = proxy.parse().map_err(|e| Error::Transport(....))?;
      self
   }
```

2023-01-19 09:06 UTC, niklasad1 commented on client/http-client/src/transport.rs
> +				match proxy.clone() {
needless clone

```suggestion
				match proxy {
```

2023-01-19 09:10 UTC, niklasad1 commented on client/http-client/src/transport.rs
> +						let proxy_uri = pr.parse().unwrap();
if the proxy URI is parsed in the builder this hasn't to be done again.

```suggestion
```

2023-01-19 09:11 UTC, niklasad1 commented on client/http-client/src/transport.rs
> +						let proxy_connector = ProxyConnector::from_proxy(connector, proxy_obj).unwrap();
we probably need to add `IoError` for this to work but no unwraps are allowed here.

```suggestion
						let proxy_connector = ProxyConnector::from_proxy(connector, proxy_obj)?;
```

2023-01-19 09:15 UTC, niklasad1 requested changes
Thank you, looks generally good but I have some comments/suggestion that needs to addressed before merging.

Also, this needs to be added to the `WS client` which I reckon would be useful as well.

2023-01-19 22:33 UTC, allquixotic commented
> Also, this needs to be added to the WS client which I reckon would be useful as well.

Agreed, but this is PR is for HTTP proxy for the HTTP client; at least, that's what I'm able/willing to work on (I'm not using the lib with a WebSocket server). Will you consider merging this just for http if the code is corrected?

2023-01-20 00:51 UTC, allquixotic commented
Weird; Clippy seems to be crashing in the compiler?

2023-01-20 08:21 UTC, niklasad1 commented
> Agreed, but this is PR is for HTTP proxy for the HTTP client; at least, that's what I'm able/willing to work on (I'm not using the lib with a WebSocket server). Will you consider merging this just for http if the code is corrected?

yeah, we can take of the `ws client` in another PR.

> Weird; Clippy seems to be crashing in the compiler?

yeah, it's known just ignore it for now https://github.com/rust-lang/rust-clippy/issues/9922

2023-01-20 10:40 UTC, niklasad1 approved these changes

2023-01-20 16:30 UTC, jsdw commented on client/http-client/src/client.rs
> +struct InvalidProxyUrl(String);
It looks like this is returned in an `Error`, so I think it should be `pub` so that it can be named by people.

2023-01-20 16:34 UTC, jsdw commented on client/http-client/src/client.rs
> +struct InvalidProxyUrl(String);
(and probably it should also be moved to live alongside `Error`? It feels a bit out of place here)

2023-01-20 16:35 UTC, jsdw commented on client/http-client/src/client.rs
> +struct InvalidProxyUrl(String);
Ah I see now' it's converted into an `anyhow::Error` before being returned; ignore me then :)

2023-01-20 16:37 UTC, jsdw approved these changes

2023-01-20 16:45 UTC, lexnv approved these changes

2023-01-23 08:45 UTC, niklasad1 commented on client/http-client/src/transport.rs
> +			#[cfg(feature = "proxy")]
```suggestion
			#[cfg(all(feature = "proxy", feature = "tls"))]
```

2023-01-23 08:46 UTC, niklasad1 commented on client/http-client/src/client.rs
> +	#[cfg(feature = "proxy")]
```suggestion
	#[cfg(all(feature = "proxy", feature = "tls"))]
```

2023-01-23 13:49 UTC, niklasad1 requested changes
Hey again,

I have looked into this crate `hyper-proxy` and it doesn't really seems to be actively maintained and brings in a bunch of outdated dependencies such as `hyper-rustls`, https://github.com/tafia/hyper-proxy/pull/28/files has been opened over a year.

I think we should find another library and or write something ourselves using tower middleware.
Sorry, figured this out before I was going to merge it.

2023-01-23 16:41 UTC, allquixotic commented
Created [issue hyper#3124](https://github.com/hyperium/hyper/issues/3124) to ask the hyper maintainers what they would suggest for HTTP proxy support. I'd rather not reinvent it within jsonrpsee. 

Supporting an http proxy within an HTTP client library is a generally useful feature that can and should be either part of the hyper crate itself, or part of a maintained crate focused on that feature. This is basic stuff that exists everywhere else I've done HTTP requests (JavaScript, .NET, Java, GLib/C, Qt/C++, Python, Ruby, etc.) It's not jsonrpsee's responsibility to code this up.

2023-01-26 13:56 UTC, closed without merging